CREATE DATABASE IF NOT EXISTS projet_reseau;

USE projet_reseau;

CREATE TABLE IF NOT EXISTS devices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(30) NOT NULL,
    mac VARCHAR(30) NOT NULL,
    interface VARCHAR(20),
    nom VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);